services:
  laravel:
    container_name: laravel
    image: 'laravel'
    environment:
      XDEBUG_MODE: coverage
    ports:
      - 9000:9000
    volumes:
      - ./:/usr/src/laravel
      - /var/run/php/php8.3-fpm.sock
      - /var:/usr/src/myapp/var
      - /vendor:/usr/src/laravel/vendor
    depends_on:
      - mysql-laravel
  mysql-laravel:
    container_name: mysql-laravel
    image: 'mysql:latest'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_HOST: mysql-laravel
    ports:
      - 3306:3306
  phpmyadmin-laravel:
    container_name: phpmyadmin-laravel
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
  nginx-laravel:
    container_name: nginx-laravel
    image: 'nginx:latest'
    depends_on:
      - laravel
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/src/laravel
      - /var/run/php/php8.3-fpm.sock
volumes:
  var:
  vendor:

